[package]
name = "pcap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packet-parser = { path = "../packet-parser" }
libc = "0.2"
nix = "0.18.0"